# Generated by Django 4.0.2 on 2022-05-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='texto',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
