# Generated by Django 4.0.2 on 2022-05-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_pessoa_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='escolaridade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
